### ISSUE TITLE
Theme options

### ISSUE THREAD

**Issue by tapsu01** [JaKooLit/Hyprland-v3.1#2]
Hi @JaKooLit ,
Previously when installing I saw the option to install Catppuccin or Tokyo theme, but in your latest update I no longer see that option but only have the option to install Tokyo theme. Is Catppuccin already installed by default? And if I don't choose to install the Tokyo theme, I will be using the Catppuccin theme (Sorry, i am newbie)

**Comment by JaKooLit** [comment]
I changed the v3.1 to v3.5 since I reconstructed the previous v3.5 and bumping to new version

I have just changed to different name as I was tweaking earlier ;)

v3.5 is a single theme tokyo night only.

The v4 will be added some themes, but for now, still catpuccin and tokyo. later down the road ill gruvbox on the mix

**Comment by tapsu01** [comment]
tks @JaKooLit ,
I think I try new your Hyprland-V4 ;)

**Comment by JaKooLit** [comment]
cool. let me know
